apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: fibervnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: fibervnn-subscriber-management-frontend-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: GATEWAY_URL
              value: http://kong-service:8000 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: fibervnn
spec:
  type: NodePort
  selector:
    app: frontend-web
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088
