apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: fibervnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.4
          ports:
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /usr/local/kong/declarative/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000
          volumeMounts:
            - name: kong-config
              mountPath: /usr/local/kong/declarative
      volumes:
        - name: kong-config
          configMap:
            name: kong-config

---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: fibervnn
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30000 
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30001
